### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by coryhouse** [shaharido1/pluralsite_test#1]
1. Components folder is misspelled
2. node_modules should be ignored to avoid uploading to GitHub
3. [You're not calling the open:src script](https://github.com/shaharido1/pluralsite_test/blob/master/package.json#L8), which is why it's not opening in the browser.

**Comment by eyapeleg** [comment]
Hey Cory,
I also tried to run the server on my machine and got the same exception. It seems like it has somethong to do with the React import...
Eyal

**Comment by coryhouse** [comment]
I ran:
1. npm install
2. npm start

And received no exceptions. 

What version of Node are your running? What OS? What exception are you receiving?

**Comment by eyapeleg** [comment]
Hi again,
I used the same configuration file you used on the starter kit.
And just to point out, the server is running, the react package isn't uploaded:

           Uncaught TypeError: Super expression must either be null or a function, not undefined

**Comment by coryhouse** [comment]
What version of Node are your running? What OS? What command are you running that is producing this exception?

**Comment by shaharido1** [comment]
Node 6.9.1
Windows 10
Npm start

**Comment by coryhouse** [comment]
Please review this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

Most importantly, try installing Node 5.12 (see above link) Node 6 has issues on some windows machines.

**Comment by shaharido1** [comment]
hey cory, first of all - thank you again for your help!
I checked and tried all the items from the "try these things first" list:

 - run the install command again
- installed eslint (again)
- downgrade to node to 5.12.
- made sure all the mentioned files start with a "." 
- run the start command from native  terminal. 
- made sure i'm using path.resolve.
- added to the eslint the line:" "root": true  ". 
- made sure no eslint plugin on my ide.

i actually couldn't find any react project (even more simplified) that run to my device.
The browser repeats the same error: "bundle.js:36248Uncaught TypeError: Super expression must either be null or a function, not undefined".

do you have maybe other projects that i could try and download? 

thanks again, Ido

**Comment by coryhouse** [comment]
Hrmm. Try out this project: github.com/coryhouse/react-slingshot

**Comment by shaharido1** [comment]
Hey Cory, 

not fully understand why, but what eventually solved it was changing the "extend" command from **"class App extends React.component"** _to_ **"class App extends Component"** (and change the import field into "import React, {PropTypes, Component} from 'react';").

do you have any idea what was the initial problem?

**Comment by coryhouse** [comment]
This fails:

`class App extends React.component`

This works:

`class App extends React.Component`

Your change worked because it referenced the named import you declared.

**Comment by coryhouse** [comment]
Anyway, glad it's working for you now! :)
